In [1]:
%matplotlib qt
import hyperspy.api as hs
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

In [3]:
s = hs.load('CBEDgpu_results_test.hdf5')

In [4]:
s

<Signal2D, title: CBEDgpu, dimensions: (40|2048, 2048)>

In [7]:
s.plot()

In [12]:
psi_im = s.original_metadata.parameters.iw_psi_im
psi_re = s.original_metadata.parameters.iw_psi_re

In [14]:
probe = psi_re + 1.0j*psi_im

In [16]:
fig, axes = plt.subplots(nrows=1, ncols=3)
axes[0].imshow(np.real(probe))
axes[1].imshow(np.imag(probe))
axes[2].imshow(np.abs(probe)**2)

In [8]:
haadf = s.inav[:, 1]
flipped_haadf = haadf.T
flipped_haadf.plot()
line = hs.roi.Line2DROI(10, 10, 20, 10)
line.add_widget(flipped_haadf)

In [ ]:
profile = line(flipped_haadf)
profile.plot()

In [11]:
flipped_haadf.plot()
aperture = hs.roi.CircleROI(10, 10, 2)
aperture.add_widget(flipped_haadf)

In [14]:
column = aperture(flipped_haadf)
column.plot()

In [17]:
integrated_intensity = column.sum(axis=[0, 1]).data

In [31]:
def line(x, a):
    return a*x# + b

In [20]:
np.array(integrated_intensity)

array([0.00091134, 0.0183372 , 0.01954502, 0.03775156, 0.03888019,
       0.0535481 , 0.05450309, 0.0708031 , 0.07181992, 0.08710291,
       0.08836545, 0.10805516, 0.1094242 , 0.12612557, 0.12769948,
       0.14143889, 0.14382017, 0.15443984, 0.15738903, 0.17072259,
       0.17330866, 0.18669242, 0.18930066, 0.19967302, 0.20178044,
       0.21107079, 0.21334468, 0.22204993, 0.22482818, 0.23702689,
       0.24019529, 0.24839935, 0.2515842 , 0.26023531, 0.2637455 ,
       0.27093139, 0.27450078, 0.28190745, 0.28555912, 0.29302513])

array([ 0.   ,  2.025,  4.05 ,  6.075,  8.1  , 10.125, 12.15 , 14.175,
       16.2  , 18.225, 20.25 , 22.275, 24.3  , 26.325, 28.35 , 30.375,
       32.4  , 34.425, 36.45 , 38.475, 40.5  , 42.525, 44.55 , 46.575,
       48.6  , 50.625, 52.65 , 54.675, 56.7  , 58.725, 60.75 , 62.775,
       64.8  , 66.825, 68.85 , 70.875, 72.9  , 74.925, 76.95 , 78.975])

In [32]:
popt, pcov = curve_fit(line, s.axes_manager['z'].axis, integrated_intensity)

In [26]:
popt

array([0.00364412, 0.01884884])

In [33]:
fig, ax = plt.subplots()
ax.plot(s.axes_manager['z'].axis, integrated_intensity, 'r-')
ax.plot(s.axes_manager['z'].axis, line(s.axes_manager['z'].axis, *popt), 'b-')

In [34]:
popt

array([0.00399759])

In [7]:
s.inav[:, 0].T.plot()